### ISSUE TITLE
Zooming does not work with Firefox

### ISSUE THREAD

**Issue by LeonhardFeiner** [skanti/ServerMeshViewer#7]
Hi, 
Thank you for your great tool.
Zooming by scrolling does only work with Chrome but not with Firefox for me. I'm using Windows 10.
Does it work for you with Firefox?

**Comment by skanti** [comment]
Hi that's true. I'll fix it if i find some time. On chrome zooming works though (if chrome is an option for you)

**Comment by skanti** [comment]
fixed
